# Generated by Django 2.1.5 on 2019-06-10 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='end_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='time',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
