# Generated by Django 2.1.5 on 2019-06-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_auto_20190610_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
