# Generated by Django 2.1.5 on 2019-06-15 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_time_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='days',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(0)]),
        ),
    ]
